### PR TITLE
change to use go 15

### PR DESCRIPTION
**Pull request by shirou**
Change to golang 1.5 which is downloaded from official site.
When using 1.5, `-build-toolchain` of gox is not required. This PR also remove build-toolchain from Makefile.

### CODE REVIEW

**Comment by voluntas** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;htOTW1F4&#x2F;107-golang-1-5"> Golang 1.5 でビルドしたバイナリをリリースする</a>

**Comment by cubicdaiya** [comment]
It seems that the lines related `gox` still remains and they are not used.

https://github.com/shiguredo/fuji/blob/feature/change-to-go-15/Makefile#L6
https://github.com/shiguredo/fuji/blob/feature/change-to-go-15/Makefile#L21

**Comment by cubicdaiya** [comment]
And won't we update version in `Godeps.json`?

https://github.com/shiguredo/fuji/blob/feature/change-to-go-15/Godeps/Godeps.json#L3

**Comment by cubicdaiya** [comment]
LGTM.

**Comment by shirou** [comment]
Thank you!

**Pull request merged**
